# -------------------------------------------------------------------------------------
#
#    Config file for snATAC-seq GE in dev human brain study
#
# -------------------------------------------------------------------------------------

__default__:
    num_cores: 1
    total_mem: 10G
    duration: 0-05:00:00

# ---------  CELL RANGER  ----------
CR_cnt_ATAC:
    num_cores: 32
    total_mem: 143G
    duration: 1-00:00:00

# -------  MUNGE SUMSTATS  ---------
standardise_phenotype_sumstats:
    num_cores: 1
    maxvmem: 20G
    duration: 3-00:00:00
sumstats_for_ldsc_hg19:
    num_cores: 1
    maxvmem: 20G
    duration: 3-00:00:00

# -----------  LDSR  ---------------
make_annot:
    num_cores: 1
    maxvmem: 10G
ldsr:
    num_cores: 1
    maxvmem: 10G
partitioned_heritability:
    num_cores: 1
    maxvmem: 20G
partitioned_heritability_conditional:
    num_cores: 1
    maxvmem: 20G

# -------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------
