# -------------------------------------------------------------------------------------
#
#    Config file for snATAC-seq GE in dev human brain study
#
# -------------------------------------------------------------------------------------

__default__:
    num_cores: 1
    total_mem: 10G
    duration: 0-05:00:00

# ---------  CELL RANGER  ----------
CR_cnt_ATAC:
    num_cores: 32
    total_mem: 143G
    duration: 1-00:00:00
snATAC_seq_QC:
    num_cores: 12
    total_mem: 128G
    duration: 1-00:00:00
snATAC_remove_batch_effects:
    num_cores: 12
    total_mem: 96G

# -------  MUNGE SUMSTATS  ---------
standardise_phenotype_sumstats:
    num_cores: 1
    total_mem: 20G
    duration: 3-00:00:00
sumstats_for_ldsc_hg19:
    num_cores: 1
    total_mem: 20G
    duration: 3-00:00:00

# -----------  LDSR  ---------------
ldsr_make_annot:
    num_cores: 1
    total_mem: 10G
ldsr_ld_scores:
    num_cores: 1
    total_mem: 10G
ldsr_stratified_baseline_v12:
    num_cores: 1
    total_mem: 20G
partitioned_heritability_conditional:
    num_cores: 1
    total_mem: 20G
LDSR_unique__make_annot:
    num_cores: 1
    total_mem: 10G
LDSR_unique_ld_scores:
    num_cores: 1
    total_mem: 10G
LDSR_unique_stratified_baseline_v12:
    num_cores: 1
    total_mem: 20G
# -------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------
