ATAC_REGIONS:
    GE:

SAMPLES_ATAC:
    14510_WGE_ATAC:
    14611_WGE_ATAC:
    14993_WGE_ATAC:

FASTQ_DIR: ../resources/fq 
REFERENCE_ATAC: ../resources/cellranger/refdata-cellranger-arc-GRCh38-2020-A-2.0.0/

MACS2_PATH: '~/.conda/envs/macs2/bin/macs2'

HARs: '../resources/sheets/HARs_capra_2019_supp_table_5.csv'

CELL_TYPES:
    CGE:
    LGE:
    MGE:
    progenitor:
#    union:

GENE_WINDOW:
    100UP_100DOWN:
    
LDSR_CELL_TYPES:
    FC.ExN:
    FC.InN:
    FC.RG:
    FC.MG:
    FC.undef:
    FC.UNION:
    LGE.InN:
    MGE.InN:
    CGE.InN:
    GE.RG:
    GE.Undef:
    GE.UNION:

ZIFFRA_CELL_TYPES:
    AstroOligo_ziffra_macs2peaks_100UP_100DOWN:
    AstroOligo_ziffra_specificpeaks_100UP_100DOWN:
    dlEN_ziffra_macs2peaks_100UP_100DOWN:
    dlEN_ziffra_specificpeaks_100UP_100DOWN:
    earlyEN_ziffra_macs2peaks_100UP_100DOWN:
    earlyEN_ziffra_specificpeaks_100UP_100DOWN:
    EndoMural_ziffra_macs2peaks_100UP_100DOWN:
    EndoMural_ziffra_specificpeaks_100UP_100DOWN:
    IN_CGE_ziffra_macs2peaks_100UP_100DOWN:
    IN_CGE_ziffra_specificpeaks_100UP_100DOWN:
    IN_MGE_ziffra_macs2peaks_100UP_100DOWN:
    IN_MGE_ziffra_specificpeaks_100UP_100DOWN:
    Insula_ziffra_macs2peaks_100UP_100DOWN:
    Insula_ziffra_specificpeaks_100UP_100DOWN:
    IPC_ziffra_macs2peaks_100UP_100DOWN:
    IPC_ziffra_specificpeaks_100UP_100DOWN:
    MGE_ziffra_macs2peaks_100UP_100DOWN:
    MGE_ziffra_specificpeaks_100UP_100DOWN:
    Microglia_ziffra_macs2peaks_100UP_100DOWN:
    Microglia_ziffra_specificpeaks_100UP_100DOWN:
    RG_ziffra_macs2peaks_100UP_100DOWN:
    RG_ziffra_specificpeaks_100UP_100DOWN:
    ulEN_ziffra_macs2peaks_100UP_100DOWN:
    ulEN_ziffra_specificpeaks_100UP_100DOWN:

COND_CELL_TYPES:
    dlEN_ziffra_macs2peaks_100UP_100DOWN:
    dlEN_ziffra_specificpeaks_100UP_100DOWN:   
    earlyEN_ziffra_macs2peaks_100UP_100DOWN:
    earlyEN_ziffra_specificpeaks_100UP_100DOWN:
    ulEN_ziffra_macs2peaks_100UP_100DOWN:
    ulEN_ziffra_specificpeaks_100UP_100DOWN:

LDSR_GWAS:
    SCZ:
    HEIGHT:

LDSR_CONDITIONS: '../resources/sheets/LDSR_conditions.tsv'


LDSR_CONDITIONAL:
    FC.ExN:
        - FC.InN
        - FC.RG
    FC.InN:
        - FC.ExN
        - FC.RG
    FC.RG:
        - FC.ExN
        - FC.InN

PEAK_EXTENSION:
    ext250bp:
    ext500bp:

