ATAC_REGIONS:
    GE:

SAMPLES_ATAC:
    14510_WGE_ATAC:
    14611_WGE_ATAC:
    14993_WGE_ATAC:

FASTQ_DIR: ../resources/fq 
REFERENCE_ATAC: ../resources/cellranger/refdata-cellranger-arc-GRCh38-2020-A-2.0.0/

MACS2_PATH: '~/.conda/envs/macs2/bin/macs2'

HARs: '../resources/sheets/HARs_capra_2019_supp_table_5.csv'

CELL_TYPES:
    CGE:
    LGE:
    MGE:
    progenitor:
    union:

SLDSR_CELL_TYPES:
    CGE:
    LGE:
    MGE:
    progenitor:

GENE_WINDOW:
    100UP_100DOWN:
    
COND_CELL_TYPES:
    dlEN_ziffra_macs2peaks:
    earlyEN_ziffra_macs2peaks:
    ulEN_ziffra_macs2peaks:
    union_neurons:

LDSR_GWAS:
    SCZ:
    HEIGHT:

LDSR_CONDITIONS: '../resources/sheets/LDSR_conditions.tsv'


LDSR_CONDITIONAL:
    FC.ExN:
        - FC.InN
        - FC.RG
    FC.InN:
        - FC.ExN
        - FC.RG
    FC.RG:
        - FC.ExN
        - FC.InN

PEAK_EXTENSION:
    ext250bp:
    ext500bp:

